const sidebars = {
  private: [ // ← 关键修改：ID 必须与 plugin 的 id 一致
    'index',
    'internal-guide',
    {
      type: 'category',
      label: '内参',
      items: [
        { type: 'autogenerated', dirName: 'internal-reference' }
      ],
    },
    {
      type: 'category',
      label: '内参代码',
      items: [
        { type: 'autogenerated', dirName: 'code' }
      ],
    },
  ],
};
export default sidebars;